package pe.com.certifakt.apifact.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum OperacionLogEnum {

	REGISTER_PAYMENT_VOUCHER("REGISTER_VOUCHER"),
	REGISTER_ANULAR_VOUCHER("REGISTER_ANULAR_VOUCHER"),
	REGISTER_SUMMARY_DOCUMENTS("REGISTER_SUMMARY_DOCUMENTS"),
	REGISTER_GUIA_REMISION("REGISTER_GUIA_REM"),
	REGISTER_OTHER_VOUCHER("REGISTER_OTHER_VOUCHER"),
//	SEND_SUNAT_RESUMEN_DIARIO("SEND_SUNAT_RC"),
	STATUS_SUNAT_VOIDED("STATUS_SUNAT_VOIDED"),
	STATUS_SUNAT_SUMMARY("STATUS_SUNAT_SUMMARY"),
	SEND_SUNAT_VOUCHER("SEND_SUNAT_VOUCHER"),
	UPDATE_BOLETA("UPDATE_BOLETA"),
	GET_STATUS_PAYMENT_VOUCHER("GET_STATUS_PAYMENT");
//	GET_STATUS("GET_STATUS");
	
	private final String operacion;

}
