package pe.com.certifakt.apifact.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum SubOperacionLogEnum {

	VALIDATE_FIELDS("VALID_FIELDS"),
	GENERATE_TEMPLATE("TEMPLATE"),
	VALIDATE_XML("VALID_XML"),
	STORAGE_FILE("STORAGE"),
	GENERATE_BEAN("GENERATE_BEAN"),
	GET_FILE("GET_FILE"),
	INSERT_BD("INSERT_BD"),
	INSERT_BD_VOIDED_DOCUMENTS("INSERT_BD_VOIDED_DOCUMENTS"),
	INSERT_BD_PAYMENTE_VOCUHER("INSERT_BD_PAYMENTE_VOCUHER"),
	INSERT_TMP_BD("INSERT_TMP_BD"),
	DELETE_BD("DELETE_BD"),
	DELETE_BD_PAYMENT_VOUCHER("DELETE_BD_PAYMENT_VOUCHER"),
	SELECT_BD("SELECT_BD"),
	UPDATE_BD("UPDATE_BD"),
	UPDATE_BD_SUMMARY("UPDATE_BD_SUMMARY"),
	UPDATE_BD_VOIDED("UPDATE_BD_VOIDED"),
	UPDATE_BD_PAYMENT_VOUCHER("UPDATE_BD_PAYMENT_VOUCHER"),
	IN_PROCESS("IN_PROCESS"),
	SEND_QUEUE("SEND_QUEUE"),
	SEND_EMAIL("SEND_EMAIL"),
	COMPLETED("COMPLETED"),
	SEND_SUNAT("SEND_SUNAT"),
	SEND_BILL("SEND_BILL");
	
	private final String subOperacion;




}
